blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path('detail/<int:pk>' , views.show_detail_blog , name="blog"),
    path('' , views.show_detail_blog), 
]

home_app/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path('' , views.show_home , name="home")
]

login_page/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path('login/' , views.show_login  , name="login"),
    path('logout' , views.user_logout , name="logout"),
]

register_page/urls.py
from django.urls import path
from .  import views

app_name = "register" 
urlpatterns = [
    path('register' , views.show_register , name="registers"), # mitoni name ba url avalie motafavert bashe 
]

site2/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static  
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home_app.urls')),
    path('' , include('login_page.urls')),
    path('' , include('register_page.urls')),
    path('blog/' , include('blog.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

# braye piade sakhi many to many 
class Category(models.Model):
    title = models.CharField(max_length=50)
    created_time = models.DateTimeField(auto_now_add=True)
     
    def __str__(self):
        return self.title

class artikle(models.Model):
    # 3 type model relation ship 
    # many to many realation ship 
    # many to one realation ship --> Forienkey 
    # one to one realation ship    
    
    
    # braye neveshtan author dastan intorie ke az ravesh manytoone estefade mishe yani 
    # be ezaye har ye user mitavan chandin ta mahgale dasht
    # one delete yani bad az inkke user pak shavad on hm pak mishe 
    
    
                                            # ( on_delete=model.set_null  , null=true )-->agar user pak shavad mitone null bashe 
                                            # ( on_delete=model.set_defult   , defult='yek meghdar bayd dashte bashe ' ) 
    author = models.ForeignKey(User , on_delete=models.CASCADE)
    title = models.CharField(max_length=10 , unique=True , unique_for_date='pub_date') 
                                                                                    # ba neveshtan uniq for date dar yek roz faghat yek title mishe sakht 
                                                                                    # --> ba neveshtan uniq=true ... dar kol project faghat mitavan yek title dasht tekrari nmishe 
   
    category = models.ManyToManyField(Category)
   
    body = models.TextField()   
    image = models.ImageField(upload_to="images/artikle")
    # be sorat khodkar yek tarikh roz ro dorost mikone 
    created_time = models.DateTimeField(auto_now_add=True)
    # be sorat khodkar tarikh ghabl ro update mikone 
    update_time = models.DateTimeField(auto_now=True)
    
    # pub date tarikh roz ro migire 
    pub_date = models.DateField(default=timezone.datetime.now())
    
    # myfile = models.FileField(upload_to='images/resome' , null=True)
    
    
    
    def __str__(self):
        return f"{self.title} - {self.body[:30]}"
    
       
    # file field hm gozine khobie braye download file and image or video ast 
    

home_app/models.py
from django.db import models

# Create your models here.

login_page/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.




class profiles(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    father_name = models.CharField(max_length=15)
    melicode = models.CharField(max_length=15)
    image = models.ImageField(upload_to='images/profile')
    
    
    
    # learning primary_key --> code meli mishe primary key 
    # for example : 
    # melicode = models.charfield(max_lenght = 50 , primary_key=true)
    # dar in model digar be jaye id ke be sorat khodkar dbsqlite primary_key klid asli ghrar midad 
    # ma be sorat dasri code meli o primary key ghrar dadim 
    
    
    
    def __str__(self):
        return self.user.username
    
        

register_page/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from blog.models import artikle
# Create your views here.


def show_detail_blog(request , pk): 
    Artikle = artikle.objects.get(id=pk)
    return render(request , 'blog/post_detail.html' , context={'Artikle' :Artikle }) 

home_app/views.py
from django.shortcuts import render
from blog.models import artikle
# Create your views here.


def show_home(request):
    
    Artikle = artikle.objects.all()
    # Artikle = artikle.object.get() --> get faghat mitone yek argument bargardone
    # Artikle = artikle.object.create() 
    return render(request , 'home_app/index.html' , context={ 'Artikle': Artikle } )

login_page/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate , login , logout

# Create your views here.

def show_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request , username=username , password=password)
        
        if user is not None:
            login(request , user)
            return redirect('home:home')
        
    return render(request , 'login_page/index.html' , context={})


def user_logout(request):
    logout(request)
    return redirect('home:home')

register_page/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.models import User
# Create your views here.

def show_register(request):
    contex = {
        'errors' : [],
    }
    if request.user.is_authenticated == True :
        return redirect('home:home')
        
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        
        if password1 != password2:
            contex['errors'].append("password is not a same ")
            return render(request , 'register_page/register.html' , contex)
                
        
        user = User.objects.create(
            username=username,
            password=password1,
            email=email
        )  
        login(request , user)
        return redirect('home:home')
    
    
    
    return render(request , 'register_page/register.html' , context={})

home_app/templates/home_app/index.html
{% extends "base.html" %}
{% load static %}


{% block title %}
  Home
{% endblock title %}

{% block content %}

    <!-- Page Content -->
    <!-- Banner Starts Here --> 
    <div class="main-banner header-text">

      
      <div class="container-fluid">
        <div class="owl-banner owl-carousel">
        {% for show_artikle in Artikle %}
          <div class="item">
            <img src="{{ show_artikle.image.url }}" alt="{{ show_artikle.title }}">
            <div class="item-content">
              <div class="main-content">
                <div class="meta-category">
                  <span>{{ show_artikle.category.first }}</span>
                </div>
                <a href="{% url 'blog:blog' show_artikle.id %}"><h4>{{ show_artikle.title }}</h4></a>
                <ul class="post-info">
                  <li><a href="#">{{ show_artikle.author.username }}</a></li>
                  <li><a href="#">{{ show_artikle.created_time }}</a></li>
                  <li><a href="#">12 Comments</a></li>
                </ul>
              </div>
            </div>
          </div>
        {% endfor %}

        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->

    <section class="blog-posts">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="assets/images/blog-post-01.jpg" alt="">
                    </div>
                    <div class="down-content">
                      <span>Lifestyle</span>
                      <a href="post-details.html"><h4>Best Template Website for HTML CSS</h4></a>
                      <ul class="post-info">
                        <li><a href="#">Admin</a></li>
                        <li><a href="#">May 31, 2020</a></li>
                        <li><a href="#">12 Comments</a></li>
                      </ul>
                      <p>Stand Blog is a free HTML CSS template for your CMS theme. You can easily adapt or customize it for any kind of CMS or website builder. You are allowed to use it for your business. You are NOT allowed to re-distribute the template ZIP file on any template collection site for the download purpose. <a rel="nofollow" href="https://templatemo.com/contact" target="_parent">Contact TemplateMo</a> for more info. Thank you.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">Beauty</a>,</li>
                              <li><a href="#">Nature</a></li>
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="assets/images/blog-post-02.jpg" alt="">
                    </div>
                    <div class="down-content">
                      <span>Healthy</span>
                      <a href="post-details.html"><h4>Etiam id diam vitae lorem dictum</h4></a>
                      <ul class="post-info">
                        <li><a href="#">Admin</a></li>
                        <li><a href="#">May 24, 2020</a></li>
                        <li><a href="#">36 Comments</a></li>
                      </ul>
                      <p>You can support us by contributing a little via PayPal. Please contact <a rel="nofollow" href="https://templatemo.com/contact" target="_parent">TemplateMo</a> via Live Chat or Email. If you have any question or feedback about this template, feel free to talk to us. Also, you may check other CSS templates such as <a rel="nofollow" href="https://templatemo.com/tag/multi-page" target="_parent">multi-page</a>, <a rel="nofollow" href="https://templatemo.com/tag/resume" target="_parent">resume</a>, <a rel="nofollow" href="https://templatemo.com/tag/video" target="_parent">video</a>, etc.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">Best Templates</a>,</li>
                              <li><a href="#">TemplateMo</a></li>
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#">Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="assets/images/blog-post-03.jpg" alt="">
                    </div>
                    <div class="down-content">
                      <span>Fashion</span>
                      <a href="post-details.html"><h4>Donec tincidunt leo nec magna</h4></a>
                      <ul class="post-info">
                        <li><a href="#">Admin</a></li>
                        <li><a href="#">May 14, 2020</a></li>
                        <li><a href="#">48 Comments</a></li>
                      </ul>
                      <p>Nullam at quam ut lacus aliquam tempor vel sed ipsum. Donec pellentesque tincidunt imperdiet. Mauris sit amet justo vulputate, cursus massa congue, vestibulum odio. Aenean elit nunc, gravida in erat sit amet, feugiat viverra leo. Phasellus interdum, diam commodo egestas rhoncus, turpis nisi consectetur nibh, in vehicula eros orci vel neque.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">HTML CSS</a>,</li>
                              <li><a href="#">Photoshop</a></li>
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#">Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="main-button">
                    <a href="blog.html">View All Posts</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                <div class="col-lg-12">
                  <div class="sidebar-item search">
                    <form id="search_form" name="gs" method="GET" action="#">
                      <input type="text" name="q" class="searchText" placeholder="type to search..." autocomplete="on">
                    </form>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                      <h2>Recent Posts</h2>
                    </div>
                    <div class="content">
                      <ul>
                        <li><a href="post-details.html">
                          <h5>Vestibulum id turpis porttitor sapien facilisis scelerisque</h5>
                          <span>May 31, 2020</span>
                        </a></li>
                        <li><a href="post-details.html">
                          <h5>Suspendisse et metus nec libero ultrices varius eget in risus</h5>
                          <span>May 28, 2020</span>
                        </a></li>
                        <li><a href="post-details.html">
                          <h5>Swag hella echo park leggings, shaman cornhole ethical coloring</h5>
                          <span>May 14, 2020</span>
                        </a></li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                      <h2>Categories</h2>
                    </div>
                    <div class="content">
                      <ul>
                        <li><a href="#">- Nature Lifestyle</a></li>
                        <li><a href="#">- Awesome Layouts</a></li>
                        <li><a href="#">- Creative Ideas</a></li>
                        <li><a href="#">- Responsive Templates</a></li>
                        <li><a href="#">- HTML5 / CSS3 Templates</a></li>
                        <li><a href="#">- Creative &amp; Unique</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                      <h2>Tag Clouds</h2>
                    </div>
                    <div class="content">
                      <ul>
                        <li><a href="#">Lifestyle</a></li>
                        <li><a href="#">Creative</a></li>
                        <li><a href="#">HTML5</a></li>
                        <li><a href="#">Inspiration</a></li>
                        <li><a href="#">Motivation</a></li>
                        <li><a href="#">PSD</a></li>
                        <li><a href="#">Responsive</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>



{% endblock content %}

login_page/templates/login_page/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V3</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static "images/icons/favicon.ico" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "fonts/iconic/css/material-design-iconic-font.min.css"%} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "vendor/animate/animate.css" %} ">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static "vendor/css-hamburgers/hamburgers.min.css" %} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "vendor/animsition/css/animsition.min.css"%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "vendor/select2/select2.min.css"%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static "vendor/daterangepicker/daterangepicker.css" %} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/main_login.css" %}">
<!--===============================================================================================-->

</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static "images/bg-01.jpg" %}');">
			<div class="wrap-login100">
		
				<form class="login100-form validate-form" method="POST">
					{% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="contact100-form-checkbox">
						<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
						<label class="label-checkbox100" for="ckb1">
							Remember me
						</label>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-90">
						<a class="txt1" href="#">
							Forgot Password?
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static "vendor/jquery/jquery-3.2.1.min.js"%}"></script>
<!--===============================================================================================-->
	<script src="{% static "vendor/animsition/js/animsition.min.js"%}"></script>
<!--===============================================================================================-->
	<script src="{% static "vendor/bootstrap/js/popper.js"%}"></script>
	<script src="{% static "vendor/bootstrap/js/bootstrap.min.js"%}"></script>
<!--===============================================================================================-->
	<script src="{% static "vendor/select2/select2.min.js"%}"></script>
<!--===============================================================================================-->
	<script src="{% static "vendor/daterangepicker/moment.min.js"%}"></script>
	<script src="{% static "vendor/daterangepicker/daterangepicker.js"%}"></script>
<!--===============================================================================================-->
	<script src="{% static "vendor/countdowntime/countdowntime.js"%}"></script>
<!--===============================================================================================-->
	<script src="{% static "js/main_login.js"%}></script>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

  
    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static "css/fontawesome.css" %}">
    <link rel="stylesheet" href="{% static "css/templatemo-stand-blog.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.css" %}"> 
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="index.html">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="about.html">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="blog.html">Blog Entries</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="post-details.html">Post Details</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact.html">Contact Us</a>
              </li>
              
              {% if request.user.is_authenticated%}
              <div class="d-flex">
                {% if request.user.first_name%}
                <div class="collapse navbar-collapse" >
                <li class="nav-item ">
                   <img src="{{ user.profiles.image.url }}" width="45px" height="40px" style="border-radius: 50%" alt="">
                </li>
                </div>

               
                  <a class="nav-link " href="">{{request.user.first_name}}</a>
                {%else%}
                  <a class="nav-link" href="">{{request.user.username}}</a>
                {%endif%}
                <div class="collapse navbar-collapse">
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'login:logout' %}">logout</a>
                </li>
                </div>
              </div>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login:login'%}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register:registers'%}">singin</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>



{% block  content%}




{% endblock  %}








    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Behance</a></li>
              <li><a href="#">Linkedin</a></li>
              <li><a href="#">Dribbble</a></li>
            </ul>
          </div>
          <div class="col-lg-12">
            <div class="copyright-text">
              <p>Copyright 2020 Stand Blog Co.
                    
                 | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static "js/custom.js" %}"></script>
    <script src="{% static "js/owl.js" %}"></script>
    <script src="{% static "js/slick.js" %}"></script>
    <script src="{% static "js/isotope.js" %}"></script>
    <script src="{% static "js/accordions.js" %}"></script>

    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

  </body>
</html>